on:
  release:
    types: [created]

name: Create Releases

permissions:
  id-token: write
  contents: read

jobs:
  build-and-publish-flux-console:
    if: startsWith(github.event.release.name, 'flux-console-v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      BUILD_CONFIG: "Release"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
      - name: Build and upload flux-console-spa.zip as SPA artifact
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        run: |
          ./build.sh
          cd dist/flux-console && zip -r flux-console-spa.zip *
          gh release upload ${{github.event.release.tag_name}} flux-console-spa.zip

  build-and-publish-flux-console-lib:
    if: startsWith(github.event.release.name, 'flux-console-lib-v')
    runs-on: ubuntu-latest
    env:
      BUILD_CONFIG: "Release"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Set VERSION Environment Variable
        run: echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV

      - name: Set VERSION Environment Variable
        run: |
          VERSION=$(echo "${{ github.event.release.name }}" | grep -oP '^.*-v(.*)$')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Build and Publish Shared Library - flux-console-lib
        if: github.repository_owner == 'embernet-ai'
        run: ./publishSharedLib.sh
